# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-64-x64-vbox4210"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"

  #config.ssh.forward_agent = true

  config.vm.synced_folder "../", "/docker-rhel-rpm"

  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    #vb.gui = true
  
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

	config.vm.provision :shell, :path => "prereqs.sh"
	config.vm.provision :shell, :path => "build.sh", :privileged => false
end
